version: '3.8'

services:
  postgres:
    container_name: flora-challenge-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: flora-challenge
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: node:20.16.0
    container_name: flora-challenge-migrate
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npx prisma migrate dev"

volumes:
  pgdata: